# Generated by Django 5.0.2 on 2024-03-14 19:09

import django.db.models.deletion
import fashion.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                (
                    "picture",
                    models.ImageField(upload_to=fashion.models.item_image_file_path),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Business", "Business"),
                            ("Casual", "Casual"),
                            ("Formal", "Formal"),
                            ("Sports", "Sports"),
                        ],
                        max_length=10,
                    ),
                ),
                ("category_url", models.CharField(blank=True, max_length=64)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="fashion.item",
                    ),
                ),
            ],
        ),
    ]
